import enum


class ContentType(int, enum.Enum):
    text = 0
    video = 1


class NodeStatus(int, enum.Enum):
    to_learn = 0  # Пользователь ещё не ознакомился с вершиной (серый цвет)
    learned = 1  # Пользователь знает вершину (зелёный цвет)
    to_repeat = 2  # Пользователю нужно повторить эту вершину (жёлтый цвет)
    finish = 3
    basic = 4



class TestStatus(int, enum.Enum):
    passed = 0
    not_passed = 1


class UpdateStatus(int, enum.Enum):
    no_updates = 0
    update_received = 1


class ContentUnit:
    def __init__(self, id: str, title: str, contentType: ContentType, summary: str, duration: str, url: str,
                 done: bool = False, liked: bool = False):
        self.id = id
        self.title = title
        self.contentType = contentType  # 0 - text, 1 - video
        self.summary = summary  # random
        self.duration = duration  # random('1 час 30 минут, 45 минут, 10 минут, ...)
        self.url = url
        self.done = done  # false
        self.liked = liked  # false

    def serialize(self):
        return {
            "id": self.id,
            "title": self.title,
            "contentType": self.contentType,
            "summary": self.summary,
            "duration": self.duration,
            "url": self.url,
            "done": self.done,
            "liked": self.liked
        }


class Update:
    def __init__(self, status: UpdateStatus, title: str, text: str, url: str, timestamp: str):
        self.status = status
        self.title = title
        self.text = text
        self.url = url
        self.timestamp = timestamp

    def serialize(self):
        if self.status == UpdateStatus.update_received:
            return {
                "status": self.status,
                "title": self.title,
                "text": self.text,
                "url": self.url,
                "timestamp": self.timestamp
            }
        else:
            return {
                "status": self.status
            }



math_graph = {
        "nodes": [['node1',
  'Целые числа',
  1,
  {'id': 'Целые числаunit1',
   'title': 'Целые числа',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/%D0%A6%D0%B5%D0%BB%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE',
   'done': False,
   'liked': False}],
 ['node2',
  'Натуральные числа',
  0,
  {'id': 'Натуральные числаunit1',
   'title': 'Натуральные числа',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D1%82%D1%83%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE',
   'done': False,
   'liked': False}],
 ['node3',
  'Действительные числа',
  0,
  {'id': 'Действительные числаunit1',
   'title': 'Действительные числа',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D1%89%D0%B5%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE',
   'done': False,
   'liked': False}],
 ['node4',
  'Степень с целым показателем',
  0,
  {'id': 'Степень с целым показателемunit1',
   'title': 'Степень с целым показателем',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'http://spacemath.xyz/stepen-s-tselym-pokazatelem/',
   'done': False,
   'liked': False}],
 ['node5',
  'Дроби, проценты, рациональные числа',
  0,
  {'id': 'Дроби, проценты, рациональные числаunit1',
   'title': 'Дроби, проценты, рациональные числа',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://biblio.mccme.ru/sites/default/files/bookfiles/stranizy.pdf',
   'done': False,
   'liked': False}],
 ['node6',
  'Степень с рациональным показателем и ее свойства',
  0,
  {'id': 'Степень с рациональным показателем и ее свойстваunit1',
   'title': 'Степень с рациональным показателем и ее свойства',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.yaklass.ru/p/algebra/10-klass/stepeni-s-ratcionalnym-pokazatelem-korni-stepennye-funktcii-11016/poniatie-stepeni-s-ratcionalnym-pokazatelem-svoistva-stepenei-11552',
   'done': False,
   'liked': False}],
 ['node7', 'Свойства степени с действительным показателем', 0],
 ['node8',
  'Степень с натуральным показателем',
  0,
  {'id': 'Степень с натуральным показателемunit1',
   'title': 'Степень с натуральным показателем',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.yaklass.ru/p/algebra/7-klass/svoistva-stepenei-s-naturalnym-pokazatelem-9095/poniatie-stepeni-s-naturalnym-pokazatelem-9093/re-df5ae963-7390-44c8-8fd8-99b83378ee26',
   'done': False,
   'liked': False}],
 ['node9', 'Свойства степени с действительным показателем', 0],
 ['node11',
  'Корень степени и его свойства',
  0,
  {'id': 'Корень степени и его свойстваunit1',
   'title': 'Корень степени и его свойства',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://sigma-center.ru/root_of_degree_n',
   'done': False,
   'liked': False}],
 ['node12',
  'Показательная функция, ее график',
  0,
  {'id': 'Показательная функция, ее графикunit1',
   'title': 'Показательная функция, ее график',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.yaklass.ru/p/algebra/11-klass/logarifmy-pokazatelnaia-i-logarifmicheskaia-funktcii-9160/svoistva-pokazatelnoi-funktcii-i-ee-grafik-10424/re-6f81546a-1197-4b52-b336-61735603da83',
   'done': False,
   'liked': False}],
 ['node13',
  'Логарифмическая функция, ее график',
  0,
  {'id': 'Логарифмическая функция, ее графикunit1',
   'title': 'Логарифмическая функция, ее график',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://dl.bsu.by/mod/book/view.php?id=10166&chapterid=1196',
   'done': False,
   'liked': False}],
 ['node14',
  'Логарифм числа',
  0,
  {'id': 'Логарифм числаunit1',
   'title': 'Логарифм числа',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://skysmart.ru/articles/mathematic/logarifmy',
   'done': False,
   'liked': False}],
 ['node15',
  'Логарифм произведения, частного, степени',
  0,
  {'id': 'Логарифм произведения, частного, степениunit1',
   'title': 'Логарифм произведения, частного, степени',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://dl.bsu.by/mod/book/view.php?id=10166&chapterid=1197',
   'done': False,
   'liked': False}],
 ['node16',
  'Десятичный и натуральный логарифмы, число е',
  0,
  {'id': 'Десятичный и натуральный логарифмы, число еunit1',
   'title': 'Десятичный и натуральный логарифмы, число е',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'http://ipo.spb.ru/iumk/Math_XXI//Modules/M_2.3.4/M_2.3.4.html#:~:text=%D0%9D%D0%B0%D1%82%D1%83%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5%20%D0%BB%D0%BE%D0%B3%D0%B0%D1%80%D0%B8%D1%84%D0%BC%D1%8B%2C%20%D1%87%D0%B8%D1%81%D0%BB%D0%BE%20e,e%3D2%2C718281828%E2%80%A6%20.',
   'done': False,
   'liked': False}],
 ['node17',
  'Преобразования выражений',
  0,
  {'id': 'Преобразования выраженийunit1',
   'title': 'Преобразования выражений',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://old.mccme.ru//exam//kn_uch/book1v4.htm',
   'done': False,
   'liked': False}],
 ['node18',
  'Преобразования тригонометрических выражений',
  0,
  {'id': 'Преобразования тригонометрических выраженийunit1',
   'title': 'Преобразования тригонометрических выражений',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'http://www.cleverstudents.ru/expressions/transformations_by_using_properties_of_logarithms.html',
   'done': False,
   'liked': False}],
 ['node19',
  'Преобразования выражений, включающих арифметические операции',
  0,
  {'id': 'Преобразования выражений, включающих арифметические операцииunit1',
   'title': 'Преобразования выражений, включающих арифметические операции',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'http://www.cleverstudents.ru/expressions/transformations_by_using_properties_of_logarithms.html',
   'done': False,
   'liked': False}],
 ['node20',
  'Преобразования выражений, включающих корни натуральной степени',
  0,
  {'id': 'Преобразования выражений, включающих корни натуральной степениunit1',
   'title': 'Преобразования выражений, включающих корни натуральной степени',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'http://www.cleverstudents.ru/expressions/transformations_by_using_properties_of_logarithms.html',
   'done': False,
   'liked': False}],
 ['node21',
  'Преобразования выражений, включающих операцию возведения в степень',
  0,
  {'id': 'Преобразования выражений, включающих операцию возведения в степеньunit1',
   'title': 'Преобразования выражений, включающих операцию возведения в степень',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'http://www.cleverstudents.ru/expressions/transformations_by_using_properties_of_logarithms.html',
   'done': False,
   'liked': False}],
 ['node22',
  'Преобразование выражений, включающих операцию логарифмирования',
  0,
  {'id': 'Преобразование выражений, включающих операцию логарифмированияunit1',
   'title': 'Преобразование выражений, включающих операцию логарифмирования',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'http://www.cleverstudents.ru/expressions/transformations_by_using_properties_of_logarithms.html',
   'done': False,
   'liked': False}],
 ['node23',
  'Модуль (абсолютная величина) числа',
  0,
  {'id': 'Модуль (абсолютная величина) числаunit1',
   'title': 'Модуль (абсолютная величина) числа',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://izamorfix.ru/matematika/algebra/modul_chisla.html',
   'done': False,
   'liked': False}],
 ['node24',
  'Свойства модуля',
  0,
  {'id': 'Свойства модуляunit1',
   'title': 'Свойства модуля',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://skysmart.ru/articles/mathematic/modul-chisla',
   'done': False,
   'liked': False}],
 ['node25',
  'Функция, область определения функции',
  0,
  {'id': 'Функция, область определения функцииunit1',
   'title': 'Функция, область определения функции',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://myalfaschool.ru/articles/funkciya#:~:text=%D0%9E%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C%D1%8E%20%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8%20f%20%D0%BD%D0%B0%D0%B7%D1%8B%D0%B2%D0%B0%D0%B5%D1%82%D1%81%D1%8F,%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B5%20%D0%BC%D0%BE%D0%B6%D0%B5%D1%82%20%D0%BF%D1%80%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D1%82%D1%8C%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F%20f.',
   'done': False,
   'liked': False}],
 ['node26',
  'Множество значений функции',
  0,
  {'id': 'Множество значений функцииunit1',
   'title': 'Множество значений функции',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikihow.com/%D0%BD%D0%B0%D0%B9%D1%82%D0%B8-%D0%BC%D0%BD%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2%D0%BE-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B9-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8',
   'done': False,
   'liked': False}],
 ['node27',
  'Основные элементарные функции',
  0,
  {'id': 'Основные элементарные функцииunit1',
   'title': 'Основные элементарные функции',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://zaochnik.com/spravochnik/matematika/funktsii/osnovnye-elementarnye-funktsii/',
   'done': False,
   'liked': False}],
 ['node28',
  'Обратная функция. График обратной функции',
  0,
  {'id': 'Обратная функция. График обратной функцииunit1',
   'title': 'Обратная функция. График обратной функции',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://1cov-edu.ru/mat-analiz/nepreryvnost-funktsii/obratnye-funktsii/grafik/',
   'done': False,
   'liked': False}],
 ['node29',
  'Линейная функция, ее график',
  0,
  {'id': 'Линейная функция, ее графикunit1',
   'title': 'Линейная функция, ее график',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://skysmart.ru/articles/mathematic/grafik-linejnoj-funkcii#:~:text=%D0%93%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%BE%D0%BC%20%D0%BB%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D0%BE%D0%B9%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8%20%D1%8F%D0%B2%D0%BB%D1%8F%D0%B5%D1%82%D1%81%D1%8F%20%D0%BF%D1%80%D1%8F%D0%BC%D0%B0%D1%8F,%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0%20%D1%81%20%D0%BE%D1%81%D1%8C%D1%8E%20%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B0%D1%82.',
   'done': False,
   'liked': False}],
 ['node30',
  'Квадратичная функция, ее график',
  0,
  {'id': 'Квадратичная функция, ее графикunit1',
   'title': 'Квадратичная функция, ее график',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://lc.rt.ru/classbook/matematika-9-klass/funktsii-i-ih-svoistva-5/935',
   'done': False,
   'liked': False}],
 ['node31',
  'Степенная функция с натуральным показателем, ее график',
  0,
  {'id': 'Степенная функция с натуральным показателем, ее графикunit1',
   'title': 'Степенная функция с натуральным показателем, ее график',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.yaklass.ru/p/algebra/9-klass/chislovye-funktcii-svoistva-chislovykh-funktcii-9132/stepennaia-funktciia-s-naturalnym-pokazatelem-12044/re-60fda931-efe7-4570-8f4b-6a43e62899de',
   'done': False,
   'liked': False}],
 ['node32',
  'Преобразования графиков: параллельный перенос, симметрия относительно осей координат',
  0,
  {'id': 'Преобразования графиков: параллельный перенос, симметрия относительно осей координатunit1',
   'title': 'Преобразования графиков: параллельный перенос, симметрия относительно осей координат',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'http://fizmat.by/math/function/preobraz_grafikov',
   'done': False,
   'liked': False}],
 ['node33',
  'Тригонометрические функции, их графики',
  0,
  {'id': 'Тригонометрические функции, их графикиunit1',
   'title': 'Тригонометрические функции, их графики',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://osiktakan.ru/alg07.html',
   'done': False,
   'liked': False}],
 ['node34',
  'Четность и нечетность функции',
  0,
  {'id': 'Четность и нечетность функцииunit1',
   'title': 'Четность и нечетность функции',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.yaklass.ru/p/algebra/9-klass/chislovye-funktcii-svoistva-chislovykh-funktcii-9132/chetnye-i-nechetnye-funktcii-opredelenie-chetnosti-i-nechetnosti-9105/re-ab47e98a-6e05-4850-81ea-744fa03b9915',
   'done': False,
   'liked': False}],
 ['node35',
  'Периодичность функции',
  0,
  {'id': 'Периодичность функцииunit1',
   'title': 'Периодичность функции',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D1%80%D0%B8%D0%BE%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F',
   'done': False,
   'liked': False}],
 ['node36',
  'Ограниченность функции',
  0,
  {'id': 'Ограниченность функцииunit1',
   'title': 'Ограниченность функции',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://foxford.ru/wiki/matematika/ogranichennye-funktsii',
   'done': False,
   'liked': False}],
 ['node37',
  'Монотонность функции. Промежутки возрастания и убывания',
  0,
  {'id': 'Монотонность функции. Промежутки возрастания и убыванияunit1',
   'title': 'Монотонность функции. Промежутки возрастания и убывания',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://function-x.ru/function_increase_decrease.html',
   'done': False,
   'liked': False}],
 ['node38',
  'Точки экстремума (локального максимума и минимума) функции',
  0,
  {'id': 'Точки экстремума (локального максимума и минимума) функцииunit1',
   'title': 'Точки экстремума (локального максимума и минимума) функции',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/%D0%AD%D0%BA%D1%81%D1%82%D1%80%D0%B5%D0%BC%D1%83%D0%BC',
   'done': False,
   'liked': False}],
 ['node39',
  'Уравнения',
  0,
  {'id': 'Уравненияunit1',
   'title': 'Уравнения',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/%D0%A3%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5',
   'done': False,
   'liked': False}],
 ['node40',
  'Квадратные уравнения',
  0,
  {'id': 'Квадратные уравненияunit1',
   'title': 'Квадратные уравнения',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://skysmart.ru/articles/mathematic/kak-reshat-kvadratnye-uravneniya',
   'done': False,
   'liked': False}],
 ['node41',
  'Рациональные уравнения',
  0,
  {'id': 'Рациональные уравненияunit1',
   'title': 'Рациональные уравнения',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.yaklass.ru/p/algebra/8-klass/kvadratnye-uravneniia-11021/reshenie-ratcionalnogo-uravneniia-svodiashchegosia-k-kvadratnomu-9118/re-1d0e092f-b0c0-44ee-81b4-7255e1d7cbfe',
   'done': False,
   'liked': False}],
 ['node42',
  'Неравенства',
  0,
  {'id': 'Неравенстваunit1',
   'title': 'Неравенства',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.yaklass.ru/p/algebra/9-klass/neravenstva-i-sistemy-neravenstv-9125/povtorenie-sposobov-resheniia-lineinykh-i-kvadratnykh-neravenstv-12311/re-c27e7bf2-e03f-45d2-ab95-c1af2a615488',
   'done': False,
   'liked': False}],
 ['node43',
  'Метод интервалов',
  0,
  {'id': 'Метод интерваловunit1',
   'title': 'Метод интервалов',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://skysmart.ru/articles/mathematic/metod-intervalov-reshenie-neravenstv',
   'done': False,
   'liked': False}],
 ['node44',
  'Наибольшее и наименьшее значения функции',
  0,
  {'id': 'Наибольшее и наименьшее значения функцииunit1',
   'title': 'Наибольшее и наименьшее значения функции',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://skysmart.ru/articles/mathematic/nahozhdeniya-naibolshego-i-naimenshego-znacheniya-funkcii',
   'done': False,
   'liked': False}],
 ['node45',
  'Иррациональные уравнения',
  0,
  {'id': 'Иррациональные уравненияunit1',
   'title': 'Иррациональные уравнения',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.matznanie.ru/xbookM0001/index.html?go=part-017*page.htm',
   'done': False,
   'liked': False}],
 ['node46',
  'Показательные уравнения',
  0,
  {'id': 'Показательные уравненияunit1',
   'title': 'Показательные уравнения',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.yaklass.ru/p/algebra/11-klass/logarifmy-pokazatelnaia-i-logarifmicheskaia-funktcii-9160/metody-resheniia-pokazatelnykh-uravnenii-10962',
   'done': False,
   'liked': False}],
 ['node47',
  'Логарифмические уравнения',
  0,
  {'id': 'Логарифмические уравненияunit1',
   'title': 'Логарифмические уравнения',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.math.md/school/praktikum/logr/logr.html',
   'done': False,
   'liked': False}],
 ['node48',
  'Использование свойств и графиков функций при решении неравенств',
  0,
  {'id': 'Использование свойств и графиков функций при решении неравенствunit1',
   'title': 'Использование свойств и графиков функций при решении неравенств',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://uztest.ru/abstracts/?idabstract=412787',
   'done': False,
   'liked': False}],
 ['node49',
  'Использование свойств и графиков функций при решении уравнений',
  0,
  {'id': 'Использование свойств и графиков функций при решении уравненийunit1',
   'title': 'Использование свойств и графиков функций при решении уравнений',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://il.tpu.ru/obuchenie-article?key=82637c627b01158a42e46b13f3213d98',
   'done': False,
   'liked': False}],
 ['node50',
  'Изображение на координатной плоскости множества решений уравнений с двумя переменными и их систем',
  0,
  {'id': 'Изображение на координатной плоскости множества решений уравнений с двумя переменными и их системunit1',
   'title': 'Изображение на координатной плоскости множества решений уравнений с двумя переменными и их систем',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://multiurok.ru/files/izobrazhenie-na-koordinatnoi-ploskosti-mnozhestva.html',
   'done': False,
   'liked': False}],
 ['node51',
  'Изображение на координатной плоскости множества решений неравенств с двумя переменными и их систем',
  0,
  {'id': 'Изображение на координатной плоскости множества решений неравенств с двумя переменными и их системunit1',
   'title': 'Изображение на координатной плоскости множества решений неравенств с двумя переменными и их систем',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://infourok.ru/metodicheskaya-razrabotka-uroka-izobrazhenie-na-koordinatnoj-ploskosti-mnozhestva-reshenij-uvnenij-i-neravenstv-s-dvumya-peremen-5648040.html',
   'done': False,
   'liked': False}],
 ['node52',
  'Тригонометрические уравнения',
  0,
  {'id': 'Тригонометрические уравненияunit1',
   'title': 'Тригонометрические уравнения',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://bymath.net/studyguide/tri/sec/tri16.php',
   'done': False,
   'liked': False}],
 ['node53',
  'Основные приемы решения систем уравнений: подстановка, алгебраическое сложение, введение новых переменных',
  0,
  {'id': 'Основные приемы решения систем уравнений: подстановка, алгебраическое сложение, введение новых переменныхunit1',
   'title': 'Основные приемы решения систем уравнений: подстановка, алгебраическое сложение, введение новых переменных',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://infourok.ru/konspekt-uroka-osnovnye-priemy-resheniya-sistem-uravnenij-podstanovka-algebraicheskoe-slozhenie-vvedenie-novyh-peremennyh-6783597.html',
   'done': False,
   'liked': False}],
 ['node54',
  'Равносильность уравнений, систем уравнений',
  0,
  {'id': 'Равносильность уравнений, систем уравненийunit1',
   'title': 'Равносильность уравнений, систем уравнений',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.yaklass.ru/p/algebra/11-klass/uravneniia-i-neravenstva-9121/ravnosilnost-uravnenii-teoremy-o-ravnosilnosti-uravnenii-12448/re-c510c3a8-26ab-4bb5-be23-54b5b5bbd8e8',
   'done': False,
   'liked': False}],
 ['node55',
  'Простейшие системы уравнений с двумя неизвестными',
  0,
  {'id': 'Простейшие системы уравнений с двумя неизвестнымиunit1',
   'title': 'Простейшие системы уравнений с двумя неизвестными',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://foxford.ru/wiki/matematika/sistemy-dvuh-lineynyh-uravneniy-s-dvumya-neizvestnymi?utm_referrer=https%3A%2F%2Fwww.google.com%2F',
   'done': False,
   'liked': False}],
 ['node56',
  'Рациональные неравенства',
  0,
  {'id': 'Рациональные неравенстваunit1',
   'title': 'Рациональные неравенства',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.matznanie.ru/xbookM0001/index.html?go=part-024*page.htm',
   'done': False,
   'liked': False}],
 ['node57',
  'Квадратные неравенства',
  0,
  {'id': 'Квадратные неравенстваunit1',
   'title': 'Квадратные неравенства',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://foxford.ru/wiki/matematika/kvadratnye-neravenstva',
   'done': False,
   'liked': False}],
 ['node58',
  'Системы линейных неравенств',
  0,
  {'id': 'Системы линейных неравенствunit1',
   'title': 'Системы линейных неравенств',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'http://mathprofi.ru/lineinye_neravenstva.html',
   'done': False,
   'liked': False}],
 ['node59',
  'Системы неравенств с одной переменной',
  0,
  {'id': 'Системы неравенств с одной переменнойunit1',
   'title': 'Системы неравенств с одной переменной',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://itest.kz/ru/ent/matematika/6-klass/lecture/sistemy-linejnyh-neravenstv-s-odnoj-peremennoj-reshenie-sistemy-linejnyh-neravenstv-s-odnoj-peremenn',
   'done': False,
   'liked': False}],
 ['node60',
  'Равносильность неравенств, систем неравенств',
  0,
  {'id': 'Равносильность неравенств, систем неравенствunit1',
   'title': 'Равносильность неравенств, систем неравенств',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.yaklass.ru/p/algebra/11-klass/uravneniia-i-neravenstva-9121/ravnosilnost-neravenstv-sistemy-i-sovokupnosti-neravenstv-9172/re-a387e720-1174-4ee6-a7bc-67b289b42195',
   'done': False,
   'liked': False}],
 ['node61',
  'Логарифмические неравенства',
  0,
  {'id': 'Логарифмические неравенстваunit1',
   'title': 'Логарифмические неравенства',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.yaklass.ru/p/algebra/11-klass/logarifmy-pokazatelnaia-i-logarifmicheskaia-funktcii-9160/metody-resheniia-logarifmicheskikh-neravenstv-9169/re-2dc8ae90-948b-44bf-bc9c-031ffc66f50a',
   'done': False,
   'liked': False}],
 ['node62',
  'Показательные неравенства',
  0,
  {'id': 'Показательные неравенстваunit1',
   'title': 'Показательные неравенства',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://skysmart.ru/articles/mathematic/pokazatelnye-neravenstva',
   'done': False,
   'liked': False}],
 ['node63',
  'Применение производной к исследованию функций и построению графиков',
  0,
  {'id': 'Применение производной к исследованию функций и построению графиковunit1',
   'title': 'Применение производной к исследованию функций и построению графиков',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://spravochnick.ru/matematika/primenenie_proizvodnoy_k_issledovaniyu_funkciy/primenenie_proizvodnoy_k_postroeniyu_grafikov_funkciy/',
   'done': False,
   'liked': False}],
 ['node64',
  'Понятие о производной функции, геометрический смысл производной',
  0,
  {'id': 'Понятие о производной функции, геометрический смысл производнойunit1',
   'title': 'Понятие о производной функции, геометрический смысл производной',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.yaklass.ru/p/algebra/11-klass/proizvodnaia-primenenie-proizvodnoi-dlia-issledovaniia-funktcii-9147/opredelenie-proizvodnoi-geometricheskii-i-fizicheskii-smysl-proizvodnoi-11223',
   'done': False,
   'liked': False}],
 ['node65',
  'Физический смысл производной, нахождение скорости для процесса, заданного формулой или графиком',
  0,
  {'id': 'Физический смысл производной, нахождение скорости для процесса, заданного формулой или графикомunit1',
   'title': 'Физический смысл производной, нахождение скорости для процесса, заданного формулой или графиком',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://studopedia.ru/24_86228_tema-vtoraya-proizvodnaya-ee-geometricheskiy-i-fizicheskiy-smisl-nahozhdenie-skorosti-dlya-protsessa-zadannogo-formuloy-i-grafikom.html',
   'done': False,
   'liked': False}],
 ['node66',
  'Уравнение касательной к графику функции',
  0,
  {'id': 'Уравнение касательной к графику функцииunit1',
   'title': 'Уравнение касательной к графику функции',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://skysmart.ru/articles/mathematic/uravnenie-kasatelnoj-k-grafiku-funkcii',
   'done': False,
   'liked': False}],
 ['node67',
  'Первообразные элементарных функций',
  0,
  {'id': 'Первообразные элементарных функцийunit1',
   'title': 'Первообразные элементарных функций',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://skysmart.ru/articles/mathematic/vychislenie-pervoobraznoj-funkcii',
   'done': False,
   'liked': False}],
 ['node68',
  'Производные суммы, разности, произведения, частного',
  0,
  {'id': 'Производные суммы, разности, произведения, частногоunit1',
   'title': 'Производные суммы, разности, произведения, частного',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://function-x.ru/function_increase_decrease.html',
   'done': False,
   'liked': False}],
 ['node69',
  'Производные основных элементарных функций',
  0,
  {'id': 'Производные основных элементарных функцийunit1',
   'title': 'Производные основных элементарных функций',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://foxford.ru/wiki/matematika/proizvodnye-elementarnyh-funkcii',
   'done': False,
   'liked': False}],
 ['node70',
  'Примеры применения интеграла в физике и геометрии',
  0,
  {'id': 'Примеры применения интеграла в физике и геометрииunit1',
   'title': 'Примеры применения интеграла в физике и геометрии',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://math4everyone.info/metodics/lekciya-primery-primeneniya-integrala-v-fizike-i-geometrii/',
   'done': False,
   'liked': False}],
 ['node71',
  'Вторая производная и ее физический смысл',
  0,
  {'id': 'Вторая производная и ее физический смыслunit1',
   'title': 'Вторая производная и ее физический смысл',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://studfile.net/preview/9577853/page:2/',
   'done': False,
   'liked': False}],
 ['node72',
  'Синус, косинус, тангенс, котангенс произвольного угла',
  0,
  {'id': 'Синус, косинус, тангенс, котангенс произвольного углаunit1',
   'title': 'Синус, косинус, тангенс, котангенс произвольного угла',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://itest.kz/ru/ent/matematika/9-klass/lecture/sinus-kosinus-tangens-kotangens-proizvolnogo-ugla',
   'done': False,
   'liked': False}],
 ['node73',
  'Радианная мера угла',
  0,
  {'id': 'Радианная мера углаunit1',
   'title': 'Радианная мера угла',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://igmt.ru/wp-content/uploads/2018/11/radian_mera_ugla.pdf',
   'done': False,
   'liked': False}],
 ['node74',
  'Основные тригонометрические тождества',
  0,
  {'id': 'Основные тригонометрические тождестваunit1',
   'title': 'Основные тригонометрические тождества',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'http://fizmat.by/math/trigonometry/trigon_formuly',
   'done': False,
   'liked': False}],
 ['node75',
  'Синус, косинус, тангенс и котангенс числа',
  0,
  {'id': 'Синус, косинус, тангенс и котангенс числаunit1',
   'title': 'Синус, косинус, тангенс и котангенс числа',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://youclever.org/book/sinus-kosinus-tangens-i-kotangens-ugla-i-chisla-1/',
   'done': False,
   'liked': False}],
 ['node76',
  'Формулы приведения',
  0,
  {'id': 'Формулы приведенияunit1',
   'title': 'Формулы приведения',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ya-znau.ru/znaniya/zn/72',
   'done': False,
   'liked': False}],
 ['node77',
  'Синус, косинус и тангенс суммы и разности двух углов',
  0,
  {'id': 'Синус, косинус и тангенс суммы и разности двух угловunit1',
   'title': 'Синус, косинус и тангенс суммы и разности двух углов',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://itest.kz/ru/ent/matematika/9-klass/lecture/formuly-summy-i-raznosti-dvuh-uglov',
   'done': False,
   'liked': False}],
 ['node78',
  'Синус и косинус двойного угла',
  0,
  {'id': 'Синус и косинус двойного углаunit1',
   'title': 'Синус и косинус двойного угла',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://zaochnik.com/spravochnik/matematika/trigonometrija/formuly-dvojnogo-ugla-v-trigonometrii/',
   'done': False,
   'liked': False}],
 ['node79',
  'Точка',
  0,
  {'id': 'Точкаunit1',
   'title': 'Точка',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Точка_(геометрия)',
   'done': False,
   'liked': False}],
 ['node80',
  'Прямая',
  0,
  {'id': 'Прямаяunit1',
   'title': 'Прямая',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Прямая',
   'done': False,
   'liked': False}],
 ['node81',
  'Угол',
  0,
  {'id': 'Уголunit1',
   'title': 'Угол',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://skysmart.ru/articles/mathematic/chto-takoe-ugol',
   'done': False,
   'liked': False}],
 ['node82',
  'Отрезок',
  0,
  {'id': 'Отрезокunit1',
   'title': 'Отрезок',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/%D0%9E%D1%82%D1%80%D0%B5%D0%B7%D0%BE%D0%BA',
   'done': False,
   'liked': False}],
 ['node83',
  'Аксиомы планиметрии',
  0,
  {'id': 'Аксиомы планиметрииunit1',
   'title': 'Отрезок',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/%D0%9E%D1%82%D1%80%D0%B5%D0%B7%D0%BE%D0%BA',
   'done': False,
   'liked': False}],
 ['node84',
  'Измерение отрезков и углов',
  0,
  {'id': 'Измерение отрезков и угловunit1',
   'title': 'Измерение отрезков и углов',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.yaklass.ru/p/geometria/7-klass/nachalnye-geometricheskie-svedeniia-14930/izmerenie-otrezkov-i-uglov-9704',
   'done': False,
   'liked': False}],
 ['node85',
  'Треугольник',
  0,
  {'id': 'Треугольникunit1',
   'title': 'Треугольник',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B5%D1%83%D0%B3%D0%BE%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA',
   'done': False,
   'liked': False}],
 ['node86',
  'Луч',
  0,
  {'id': 'Лучunit1',
   'title': 'Луч',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/%D0%9B%D1%83%D1%87_(%D0%B3%D0%B5%D0%BE%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D1%8F)',
   'done': False,
   'liked': False}],
 ['node87',
  'Геометрические построения - окружность',
  0,
  {'id': 'Геометрические построения - окружностьunit1',
   'title': 'Луч',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/%D0%9B%D1%83%D1%87_(%D0%B3%D0%B5%D0%BE%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D1%8F)',
   'done': False,
   'liked': False}],
 ['node88',
  'Признаки и свойства равенства треугольников',
  0,
  {'id': 'Признаки и свойства равенства треугольниковunit1',
   'title': 'Признаки и свойства равенства треугольников',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://zftsh.online/articles/5174',
   'done': False,
   'liked': False}],
 ['node89',
  'Параллельность. Сумма углов треугольника',
  0,
  {'id': 'Параллельность. Сумма углов треугольникаunit1',
   'title': 'Параллельность. Сумма углов треугольника',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://mathus.ru/math/parallel.pdf',
   'done': False,
   'liked': False}],
 ['node90',
  'Геометрические неравенства',
  0,
  {'id': 'Геометрические неравенстваunit1',
   'title': 'Геометрические неравенства',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://old.mccme.ru//free-books//prasolov/planim/gl9.htm',
   'done': False,
   'liked': False}],
 ['node91',
  'Периметр и площадь треугольника',
  0,
  {'id': 'Периметр и площадь треугольникаunit1',
   'title': 'Периметр и площадь треугольника',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://izamorfix.ru/matematika/planimetriya/perimetr_ploschad_treug.html',
   'done': False,
   'liked': False}],
 ['node92',
  'Геометрическое место точек',
  0,
  {'id': 'Геометрическое место точекunit1',
   'title': 'ГМТ',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://old.mccme.ru//free-books//prasolov/planim/gl7.htm#:~:text=1.,%D0%B4%D0%BB%D1%8F%20%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D1%85%20%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%BE%20%D1%8D%D1%82%D0%BE%20%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%BE.&text=%D0%B0)%20%D1%82%D0%BE%D1%87%D0%BA%D0%B8%2C%20%D0%BE%D0%B1%D0%BB%D0%B0%D0%B4%D0%B0%D1%8E%D1%89%D0%B8%D0%B5%20%D1%82%D1%80%D0%B5%D0%B1%D1%83%D0%B5%D0%BC%D1%8B%D0%BC%20%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%BE%D0%BC,%D1%84%D0%B8%D0%B3%D1%83%D1%80%D1%8B%20F%20%D0%BE%D0%B1%D0%BB%D0%B0%D0%B4%D0%B0%D1%8E%D1%82%20%D1%82%D1%80%D0%B5%D0%B1%D1%83%D0%B5%D0%BC%D1%8B%D0%BC%20%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%BE%D0%BC.',
   'done': False,
   'liked': False}],
 ['node93',
  'Касательная к окружности',
  0,
  {'id': 'Касательная к окружностиunit1',
   'title': 'Касательная к окружности',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://www.yaklass.ru/p/geometria/8-klass/okruzhnost-9230/kasatelnaia-i-okruzhnost-9242/re-ca89ade5-1388-4df8-af6d-be4437358f63',
   'done': False,
   'liked': False}],
 ['node94',
  'Средняя линия треугольника',
  0,
  {'id': 'Средняя линия треугольникаunit1',
   'title': 'Средняя линия треугольника',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://foxford.ru/wiki/matematika/srednyaya-liniya-treugolnika?utm_referrer=https%3A%2F%2Fwww.google.com%2F',
   'done': False,
   'liked': False}],
 ['node95',
  'Трапеция',
  0,
  {'id': 'Трапецияunit1',
   'title': 'Трапеция',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Трапеция',
   'done': False,
   'liked': False}],
 ['node96',
  'Многоугольник',
  0,
  {'id': 'Многоугольникunit1',
   'title': 'Многоугольник',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Многоугольник',
   'done': False,
   'liked': False}],
 ['node97',
  'Теорема Фалеса. Теорема о пропорциональных отрезках',
  0,
  {'id': 'Теорема Фалеса. Теорема о пропорциональных отрезкахunit1',
   'title': 'Теорема Фалеса о пропорциональных отрезках',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Теорема_Фалеса_о_пропорциональных_отрезках',
   'done': False,
   'liked': False}],
 ['node98',
  'Биссектриса, срединный перпендикуляр, медиана треугольника',
  0,
  {'id': 'Биссектриса, срединный перпендикуляр, медиана треугольникаunit1',
   'title': 'Теорема Фалеса о пропорциональных отрезках',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Теорема_Фалеса_о_пропорциональных_отрезках',
   'done': False,
   'liked': False}],
 ['node99',
  'Параллелограмм',
  0,
  {'id': 'Параллелограммunit1',
   'title': 'Параллелограмм',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Параллелограмм',
   'done': False,
   'liked': False}],
 ['node100',
  'Подобные треугольники',
  0,
  {'id': 'Подобные треугольникиunit1',
   'title': 'Признаки подобия треугольников',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Признаки_подобия_треугольников',
   'done': False,
   'liked': False}],
 ['node101',
  'Площадь чертырёхугольника',
  0,
  {'id': 'Площадь чертырёхугольникаunit1',
   'title': 'Признаки подобия треугольников',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Признаки_подобия_треугольников',
   'done': False,
   'liked': False}],
 ['node102',
  'Теорема Пифагора',
  0,
  {'id': 'Теорема Пифагораunit1',
   'title': 'Теорема Пифагора',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Теорема_Пифагора',
   'done': False,
   'liked': False}],
 ['node103',
  'Теорема Менелая и теорема Чевы',
  0,
  {'id': 'Теорема Менелая и теорема Чевыunit1',
   'title': 'Теорема Менелая',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Теорема_Менелая',
   'done': False,
   'liked': False}],
 ['node104',
  'Вписанный угол',
  0,
  {'id': 'Вписанный уголunit1',
   'title': 'Вписанный угол',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Вписанный_угол',
   'done': False,
   'liked': False}],
 ['node105',
  'Декартовы координаты на плоскости',
  0,
  {'id': 'Декартовы координаты на плоскостиunit1',
   'title': 'Прямоугольная система координат',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Прямоугольная_система_координат',
   'done': False,
   'liked': False}],
 ['node106', 'Пропорциональные отрезки в круге', 0],
 ['node107',
  'Векторы',
  0,
  {'id': 'Векторыunit1',
   'title': 'Вектор (геометрия)',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Вектор_(геометрия)',
   'done': False,
   'liked': False}],
 ['node108',
  'Теорема синусов',
  0,
  {'id': 'Теорема синусовunit1',
   'title': 'Теорема синусов',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Теорема_синусов',
   'done': False,
   'liked': False}],
 ['node109',
  'Теорема косинусов',
  0,
  {'id': 'Теорема косинусовunit1',
   'title': 'Теорема косинусов',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Теорема_косинусов',
   'done': False,
   'liked': False}],
 ['node110',
  'Аксиомы стереометрии',
  0,
  {'id': 'Аксиомы стереометрииunit1',
   'title': 'Теорема косинусов',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Теорема_косинусов',
   'done': False,
   'liked': False}],
 ['node111',
  'Проекция, наклонная',
  0,
  {'id': 'Проекция, наклоннаяunit1',
   'title': 'Проекция, наклонная',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://en.wikipedia.org/wiki/Oblique_projection',
   'done': False,
   'liked': False}],
 ['node112',
  'Многогранник',
  0,
  {'id': 'Многогранникunit1',
   'title': 'Проекция, наклонная',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Многогранник',
   'done': False,
   'liked': False}],
 ['node113',
  'Плоскость',
  0,
  {'id': 'Плоскостьunit1',
   'title': 'Проекция, наклонная',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Плоскость',
   'done': False,
   'liked': False}],
 ['node114',
  'Взаимное расположение прямых и плоскостей в стереометрии',
  0,
  {'id': 'Взаимное расположение прямых и плоскостей в стереометрииunit1',
   'title': 'Взаимное расположение прямых и плоскостей в стереометрии',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://interneturok.ru/lesson/geometry/10-klass/parallelnost-pryamyh-i-ploskostej/vzaimnoe-raspolozhenie-pryamyh-i-ploskostey-v-prostranstve-bazovyy-uroven',
   'done': False,
   'liked': False}],
 ['node115',
  'Построение сечений в стереометрии',
  0,
  {'id': 'Построение сечений в стереометрииunit1',
   'title': 'Сечение многогранников',
   'contentType': 0,
   'summary': 'https://ru.wikipedia.org/wiki/Сечение_многогранников',
   'duration': '~30 мнут',
   'url': '',
   'done': False,
   'liked': False}],
 ['node116',
  'Параллелепипед',
  0,
  {'id': 'Параллелепипедunit1',
   'title': 'Параллелепипед',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Параллелепипед',
   'done': False,
   'liked': False}],
 ['node117',
  'Теорема о трех перпендикулярах',
  0,
  {'id': 'Теорема о трех перпендикулярахunit1',
   'title': 'Теорема о трех перпендикулярах',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Теорема_о_трёх_перпендикулярах',
   'done': False,
   'liked': False}],
 ['node118',
  'Свойства и формулы для призмы',
  0,
  {'id': 'Свойства и формулы для призмыunit1',
   'title': 'Свойства призмы',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Призма_(геометрия)#:~:text=Свойства-,призмы,-%5Bправить%20%7C',
   'done': False,
   'liked': False}],
 ['node119',
  'Призма',
  0,
  {'id': 'Призмаunit1',
   'title': 'Призма (геометрия)',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Призма_(геометрия)',
   'done': False,
   'liked': False}],
 ['node120',
  'Тетраэдр',
  0,
  {'id': 'Тетраэдрunit1',
   'title': 'Тетраэдр',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Тетраэдр',
   'done': False,
   'liked': False}],
 ['node121',
  'Пирамида',
  0,
  {'id': 'Пирамидаunit1',
   'title': 'Пирамида',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Пирамида',
   'done': False,
   'liked': False}],
 ['node122',
  'Свойства и формулы для тетраэдра',
  0,
  {'id': 'Свойства и формулы для тетраэдраunit1',
   'title': 'Формулы тетраэдра в декартовых координатах в пространстве',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D1%82%D1%80%D0%B0%D1%8D%D0%B4%D1%80#:~:text=%D1%82%D0%B5%D1%82%D1%80%D0%B0%D1%8D%D0%B4%D1%80%D0%B0%20%5B6%5D-,%D0%A4%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D1%8B%20%D1%82%D0%B5%D1%82%D1%80%D0%B0%D1%8D%D0%B4%D1%80%D0%B0%20%D0%B2%20%D0%B4%D0%B5%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D0%B2%D1%8B%D1%85%20%D0%BA%D0%BE%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B0%D1%82%D0%B0%D1%85%20%D0%B2%20%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%BD%D1%81%D1%82%D0%B2%D0%B5,-%5B%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C%20%7C',
   'done': False,
   'liked': False}],
 ['node123',
  'Шар',
  0,
  {'id': 'Шарunit1',
   'title': 'Формулы тетраэдра в декартовых координатах в пространстве',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D1%82%D1%80%D0%B0%D1%8D%D0%B4%D1%80#:~:text=%D1%82%D0%B5%D1%82%D1%80%D0%B0%D1%8D%D0%B4%D1%80%D0%B0%20%5B6%5D-,%D0%A4%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D1%8B%20%D1%82%D0%B5%D1%82%D1%80%D0%B0%D1%8D%D0%B4%D1%80%D0%B0%20%D0%B2%20%D0%B4%D0%B5%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D0%B2%D1%8B%D1%85%20%D0%BA%D0%BE%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B0%D1%82%D0%B0%D1%85%20%D0%B2%20%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%BD%D1%81%D1%82%D0%B2%D0%B5,-%5B%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C%20%7C',
   'done': False,
   'liked': False}],
 ['node124',
  'Описанные вокруг сферы сущности',
  0,
  {'id': 'Описанные вокруг сферы сущностиunit1',
   'title': 'Формулы тетраэдра в декартовых координатах в пространстве',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D1%82%D1%80%D0%B0%D1%8D%D0%B4%D1%80#:~:text=%D1%82%D0%B5%D1%82%D1%80%D0%B0%D1%8D%D0%B4%D1%80%D0%B0%20%5B6%5D-,%D0%A4%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D1%8B%20%D1%82%D0%B5%D1%82%D1%80%D0%B0%D1%8D%D0%B4%D1%80%D0%B0%20%D0%B2%20%D0%B4%D0%B5%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D0%B2%D1%8B%D1%85%20%D0%BA%D0%BE%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B0%D1%82%D0%B0%D1%85%20%D0%B2%20%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%BD%D1%81%D1%82%D0%B2%D0%B5,-%5B%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C%20%7C',
   'done': False,
   'liked': False}],
 ['node125',
  'Формулы для объема и площади пирамиды',
  0,
  {'id': 'Формулы для объема и площади пирамидыunit1',
   'title': 'Формулы тетраэдра в декартовых координатах в пространстве',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D1%82%D1%80%D0%B0%D1%8D%D0%B4%D1%80#:~:text=%D1%82%D0%B5%D1%82%D1%80%D0%B0%D1%8D%D0%B4%D1%80%D0%B0%20%5B6%5D-,%D0%A4%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D1%8B%20%D1%82%D0%B5%D1%82%D1%80%D0%B0%D1%8D%D0%B4%D1%80%D0%B0%20%D0%B2%20%D0%B4%D0%B5%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D0%B2%D1%8B%D1%85%20%D0%BA%D0%BE%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B0%D1%82%D0%B0%D1%85%20%D0%B2%20%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%BD%D1%81%D1%82%D0%B2%D0%B5,-%5B%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C%20%7C',
   'done': False,
   'liked': False}],
 ['node126',
  'Двугранный угол',
  0,
  {'id': 'Двугранный уголunit1',
   'title': 'Двугранный угол',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Двугранный_угол',
   'done': False,
   'liked': False}],
 ['node127', 'Сфера', 0],
 ['node128',
  'Объем и площадь боковой и полной поверхностей цилиндра',
  0,
  {'id': 'Объем и площадь боковой и полной поверхностей цилиндраunit1',
   'title': 'Цилиндр',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Цилиндр',
   'done': False,
   'liked': False}],
 ['node129',
  'Конус',
  0,
  {'id': 'Конусunit1',
   'title': 'Конус',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Конус',
   'done': False,
   'liked': False}],
 ['node130',
  'Цилиндр',
  0,
  {'id': 'Цилиндрunit1',
   'title': 'Цилиндр',
   'contentType': 0,
   'summary': 'sdsd',
   'duration': '~30 мнут',
   'url': 'https://ru.wikipedia.org/wiki/Цилиндр',
   'done': False,
   'liked': False}]],
            "edges": [
        ["node1", "node4"], ["node1", "node5"], ["node4", "node6"], ["node2", "node5"], ["node2", "node8"],
        ["node5", "node6"],
        ["node3", "node25"], ["node3", "node7"], ["node3", "node23"], ["node3", "node5"], ["node6", "node7"],
        ["node6", "node12"],
        ["node17", "node18"], ["node17", "node19"], ["node17", "node20"], ["node17", "node21"], ["node17", "node22"],
        ["node17", "node23"],
        ["node14", "node17"], ["node72", "node109"], ["node72", "node108"], ["node72", "node76"], ["node72", "node75"],
        ["node72", "node74"],
        ["node72", "node73"], ["node33", "node72"], ["node74", "node76"], ["node74", "node77"], ["node74", "node78"],
        ["node25", "node64"],
        ["node25", "node39"], ["node25", "node26"], ["node25", "node27"], ["node27", "node29"], ["node27", "node31"],
        ["node42", "node57"],
        ["node27", "node33"], ["node27", "node28"], ["node27", "node69"], ["node53", "node49"], ["node54", "node53"],
        ["node55", "node53"],
        ["node42", "node43"], ["node42", "node56"], ["node42", "node58"], ["node42", "node61"], ["node42", "node62"],
        ["node42", "node90"],
        ["node39", "node42"], ["node39", "node46"], ["node39", "node40"], ["node39", "node41"], ["node39", "node52"],
        ["node39", "node54"],
        ["node39", "node55"], ["node24", "node39"], ["node39", "node48"], ["node39", "node47"], ["node57", "node58"],
        ["node64", "node65"],
        ["node56", "node58"], ["node61", "node58"], ["node62", "node58"], ["node64", "node66"], ["node64", "node69"],
        ["node64", "node67"],
        ["node38", "node64"], ["node13", "node14"], ["node13", "node36"], ["node13", "node47"], ["node31", "node13"],
        ["node12", "node13"],
        ["node33", "node18"], ["node33", "node35"], ["node33", "node34"], ["node33", "node37"], ["node33", "node108"],
        ["node33", "node109"],
        ["node33", "node52"], ["node81", "node33"], ["node33", "node81"], ["node71", "node63"], ["node68", "node71"],
        ["node69", "node71"],
        ["node44", "node48"], ["node60", "node48"], ["node63", "node48"], ["node48", "node51"], ["node28", "node29"],
        ["node28", "node31"],
        ["node28", "node32"], ["node28", "node37"], ["node26", "node28"], ["node37", "node38"], ["node26", "node38"],
        ["node36", "node38"],
        ["node38", "node44"], ["node11", "node12"], ["node31", "node12"], ["node12", "node47"], ["node44", "node49"],
        ["node63", "node49"],
        ["node49", "node50"], ["node78", "node52"], ["node77", "node78"], ["node14", "node15"], ["node14", "node16"],
        ["node7", "node11"],
        ["node8", "node7"], ["node30", "node37"], ["node29", "node30"], ["node34", "node35"], ["node37", "node34"],
        ["node34", "node36"],
        ["node76", "node77"], ["node23", "node24"], ["node59", "node60"], ["node58", "node59"], ["node47", "node46"],
        ["node41", "node45"],
        ["node65", "node68"], ["node67", "node65"], ["node67", "node70"], ["node66", "node68"], ["node127", "node124"],
        ["node129", "node124"],
        ["node119", "node124"], ["node116", "node124"], ["node120", "node124"], ["node121", "node124"],
        ["node121", "node130"],
        ["node121", "node127"], ["node121", "node125"], ["node121", "node129"], ["node116", "node121"],
        ["node123", "node121"],
        ["node120", "node121"], ["node112", "node121"], ["node121", "node119"], ["node119", "node118"],
        ["node119", "node116"], ["node120", "node119"], ["node112", "node119"], ["node112", "node113"],
        ["node112", "node110"], ["node112", "node116"], ["node113", "node112"], ["node110", "node112"],
        ["node112", "node120"],
        ["node113", "node114"], ["node113", "node117"], ["node113", "node115"], ["node113", "node126"],
        ["node126", "node113"], ["node127", "node123"], ["node127", "node129"], ["node127", "node130"],
        ["node126", "node127"], ["node116", "node117"], ["node114", "node117"], ["node111", "node117"],
        ["node83", "node110"],
        ["node115", "node110"], ["node110", "node111"], ["node111", "node114"],
        ["node120", "node122"], ["node130", "node128"], ["node99", "node116"],
        ["node79", "node80"], ["node80", "node79"], ["node87", "node92"], ["node87", "node93"], ["node87", "node97"],
        ["node87", "node109"],
        ["node80", "node87"], ["node85", "node89"], ["node85", "node98"], ["node85", "node92"], ["node85", "node94"],
        ["node101", "node85"], ["node85", "node102"], ["node85", "node91"], ["node85", "node83"], ["node85", "node82"],
        ["node82", "node85"],
        ["node97", "node106"], ["node97", "node105"], ["node97", "node107"], ["node97", "node102"],
        ["node97", "node100"], ["node97", "node103"],
        ["node97", "node108"], ["node95", "node97"], ["node84", "node97"], ["node97", "node101"], ["node89", "node97"],
        ["node82", "node84"],
        ["node82", "node81"], ["node81", "node82"], ["node81", "node84"], ["node81", "node80"], ["node80", "node81"],
        ["node79", "node87"],
        ["node98", "node101"], ["node96", "node101"],
        ["node101", "node99"], ["node101", "node108"], ["node107", "node101"], ["node101", "node109"],
        ["node101", "node95"], ["node102", "node101"], ["node105", "node101"],
        ["node108", "node109"], ["node104", "node108"], ["node100", "node108"],
        ["node99", "node108"], ["node109", "node108"], ["node102", "node108"],
        ["node86", "node89"], ["node86", "node83"], ["node83", "node86"], ["node99", "node109"], ["node91", "node109"],
        ["node102", "node109"], ["node98", "node100"], ["node94", "node100"], ["node89", "node100"],
        ["node100", "node104"], ["node88", "node94"],
        ["node98", "node94"], ["node94", "node91"], ["node94", "node95"], ["node88", "node89"],
        ["node84", "node89"], ["node89", "node96"], ["node89", "node90"], ["node107", "node99"],
        ["node91", "node99"], ["node96", "node99"], ["node98", "node99"],
        ["node90", "node96"], ["node96", "node95"], ["node92", "node98"], ["node92", "node91"], ["node80", "node93"],
        ["node93", "node104"],
        ["node104", "node106"], ["node103", "node106"], ["node105", "node107"], ["node102", "node105"],
        ["node84", "node88"]]
    }


id_to_index_math = {row[0]: index for index, row in enumerate(math_graph["nodes"])}